FROM node:20-alpine

RUN apk add --no-cache curl

WORKDIR /app

COPY package.json ./
RUN npm install --production

COPY printer-mock-server.js ./

RUN mkdir -p /app/jobs

CMD ["node", "printer-mock-server.js"]
