FROM node:20-alpine

RUN apk add --no-cache curl

WORKDIR /app

COPY package*.json ./
RUN npm install --omit=dev

COPY src ./src

ENV NODE_ENV=test
ENV EXEF_LOCAL_SERVICE_HOST=0.0.0.0
ENV EXEF_LOCAL_SERVICE_PORT=3030

EXPOSE 3030

CMD ["node", "src/local-service/server.js"]
